server:
  port: 8081


mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill01?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf-8
    name: seckill01
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource